[package]
name = "psqnet_transport"
version = "0.1.0"
edition = "2024"

[lib]
name = "psqnet_transport"
path = "src/lib.rs"


[dependencies]
zeroize = { version = "*" }
constant_time_eq = { version = "*" }

[lints.clippy]
type_complexity = "allow"
large_enum_variant = "allow"
absurd_extreme_comparisons = "allow"
unusual_byte_groupings = "allow"
needless_range_loop = "allow"
