use crate::crypto::*;

/* START OF MESSAGE DEFINITION */

pub const PAYLOAD_START: usize = 0;

/* START OF MESSAGE TAIL DEFINITION */

pub const PAYLOAD_REV_START: usize = PAYLOAD_TAG_REV_END;

pub const PAYLOAD_TAG_REV_END: usize = PAYLOAD_TAG_REV_START + PAYLOAD_TAG_LEN;
pub const PAYLOAD_TAG_LEN: usize = aes256::TAG_LEN;
pub const PAYLOAD_TAG_REV_START: usize = ONLINE_SIGN_REV_END;

pub const ONLINE_SIGN_REV_END: usize = ONLINE_SIGN_REV_START + ONLINE_SIGN_LEN;
pub const ONLINE_SIGN_LEN: usize = mldsa87::SIGN_LEN;
pub const ONLINE_SIGN_REV_START: usize = ONLINE_SIGN_TAG_REV_END;

pub const ONLINE_SIGN_TAG_REV_END: usize = ONLINE_SIGN_TAG_REV_START + ONLINE_SIGN_TAG_LEN;
pub const ONLINE_SIGN_TAG_LEN: usize = aes256::TAG_LEN;
pub const ONLINE_SIGN_TAG_REV_START: usize = 0;

/* START OF MISC CONSTANTS */
