use std::ops::Range;

use crate::crypto::*;

/* START OF MESSAGE DEFINITION */

pub const PAYLOAD_LEN_START: usize = 0;
pub const PAYLOAD_LEN_LEN: usize = 2;
pub const PAYLOAD_LEN_END: usize = PAYLOAD_LEN_START + PAYLOAD_LEN_LEN;
pub const PAYLOAD_LEN_RANGE: Range<usize> = PAYLOAD_LEN_START..PAYLOAD_LEN_END;

pub const PAYLOAD_START: usize = PAYLOAD_LEN_END;

/* START OF MESSAGE TAIL DEFINITION */

pub const KEY_BUNDLE_REV_START: usize = PAYLOAD_TAG_REV_END;

pub const PAYLOAD_TAG_REV_END: usize = PAYLOAD_TAG_REV_START + PAYLOAD_TAG_LEN;
pub const PAYLOAD_TAG_LEN: usize = aes256::TAG_LEN;
pub const PAYLOAD_TAG_REV_START: usize = ONLINE_SIGNATURE_REV_END;

pub const ONLINE_SIGNATURE_REV_END: usize = ONLINE_SIGNATURE_REV_START + ONLINE_SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_LEN: usize = mldsa87::SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_REV_START: usize = ONLINE_SIGNATURE_TAG_REV_END;

pub const ONLINE_SIGNATURE_TAG_REV_END: usize = ONLINE_SIGNATURE_TAG_REV_START + ONLINE_SIGNATURE_TAG_LEN;
pub const ONLINE_SIGNATURE_TAG_LEN: usize = aes256::TAG_LEN;
pub const ONLINE_SIGNATURE_TAG_REV_START: usize = 0;

/* START OF LENGTH CONSTANTS */

pub const HEADER_LEN: usize = super::shared::SEGMENT_HEADER_END;

pub const MESSAGE_GCM_TOTAL: u32 = 2;
