/* HANDSHAKE FLAG CONSTANTS */

pub const HANDSHAKE_FLAG_USE_RESUMPTION: u8 = 0b1;
// pub const HANDSHAKE_FLAG_FULL_HANDSHAKE: u8 = 0b10;
pub const HANDSHAKE_FLAG_DENY_FALLBACK: u8 = 0b100;

pub const HANDSHAKE_FLAGS_MASK: u8 = 0b111;
