use std::ops::Range;

use crate::crypto::*;

/* START OF MESSAGE DEFINITION */

pub const INITIALIZE_UID_START: usize = super::shared::SEGMENT_HEADER_END;
pub const INITIALIZE_UID_LEN: usize = 8;
pub const INITIALIZE_UID_END: usize = INITIALIZE_UID_START + INITIALIZE_UID_LEN;
pub const INITIALIZE_UID_RANGE: Range<usize> = INITIALIZE_UID_START..INITIALIZE_UID_END;

pub const HANDSHAKE_VERSION_START: usize = INITIALIZE_UID_END;
pub const HANDSHAKE_VERSION_LEN: usize = 1;
pub const HANDSHAKE_VERSION_END: usize = HANDSHAKE_VERSION_IDX + HANDSHAKE_VERSION_LEN;
pub const HANDSHAKE_VERSION_IDX: usize = HANDSHAKE_VERSION_START;
pub const HANDSHAKE_VERSION_VALUE: u8 = 1;

pub const HANDSHAKE_FLAGS_START: usize = HANDSHAKE_VERSION_END;
pub const HANDSHAKE_FLAGS_LEN: usize = 1;
pub const HANDSHAKE_FLAGS_END: usize = HANDSHAKE_FLAGS_IDX + HANDSHAKE_FLAGS_LEN;
pub const HANDSHAKE_FLAGS_IDX: usize = HANDSHAKE_FLAGS_START;

pub const EPHEMERAL_ENC_KEY_START: usize = HANDSHAKE_FLAGS_END;
pub const EPHEMERAL_ENC_KEY_LEN: usize = mlkem1024::ENCAPSULATION_KEY_LEN;
pub const EPHEMERAL_ENC_KEY_END: usize = EPHEMERAL_ENC_KEY_START + EPHEMERAL_ENC_KEY_LEN;
pub const EPHEMERAL_ENC_KEY_RANGE: Range<usize> = EPHEMERAL_ENC_KEY_START..EPHEMERAL_ENC_KEY_END;

pub const NEW_SOCKET_ID_START: usize = EPHEMERAL_ENC_KEY_END;
pub const NEW_SOCKET_ID_LEN: usize = 4;
pub const NEW_SOCKET_ID_END: usize = NEW_SOCKET_ID_START + NEW_SOCKET_ID_LEN;
pub const NEW_SOCKET_ID_RANGE: Range<usize> = NEW_SOCKET_ID_START..NEW_SOCKET_ID_END;

pub const PREMESSAGE_DEFAULT_HANDSHAKE_RANGE: Range<usize> = 0..RESUMPTION_TOKEN_END;

pub const RESUMPTION_TOKEN_START: usize = NEW_SOCKET_ID_END;
pub const RESUMPTION_TOKEN_LEN: usize = 32;
pub const RESUMPTION_TOKEN_END: usize = RESUMPTION_TOKEN_START + RESUMPTION_TOKEN_LEN;
pub const RESUMPTION_TOKEN_RANGE: Range<usize> = RESUMPTION_TOKEN_START..RESUMPTION_TOKEN_END;

pub const PREMESSAGE_RESUMPTION_RANGE: Range<usize> = 0..RESUMPTION_TOKEN_END;

pub const RESUMPTION_ENCRYPTION_START: usize = RESUMPTION_TOKEN_END;

pub const PAYLOAD_START: usize = RESUMPTION_TOKEN_END;

/* START OF MESSAGE TAIL DEFINITION */

pub const PAYLOAD_REV_START: usize = BUNDLE_UID_XOR_REV_END;

pub const BUNDLE_UID_XOR_REV_END: usize = BUNDLE_UID_XOR_REV_START + BUNDLE_UID_XOR_LEN;
pub const BUNDLE_UID_XOR_LEN: usize = 16;
pub const BUNDLE_UID_XOR_REV_START: usize = ONLINE_SIGNATURE_REV_END;

pub const ONLINE_SIGNATURE_REV_END: usize = ONLINE_SIGNATURE_REV_START + ONLINE_SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_LEN: usize = mldsa87::SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_REV_START: usize = RESUMPTION_TAG_REV_END;

pub const RESUMPTION_TAG_REV_END: usize = RESUMPTION_TAG_REV_START + RESUMPTION_TAG_LEN;
pub const RESUMPTION_TAG_LEN: usize = aes256::TAG_LEN;
pub const RESUMPTION_TAG_REV_START: usize = 0;

/* START OF GENERAL CONSTANTS */

pub const NULL_KEY_ID: u32 = 0;

pub const RESUMPTION_KEY_LEN: usize = 64;

pub const HEADER_LEN: usize = INITIALIZE_UID_END;

pub const MESSAGE_LEN_WITHOUT_SIGN: usize = NEW_SOCKET_ID_END;
pub const MESSAGE_LEN_WITH_FULL: usize = RESUMPTION_TOKEN_END + RESUMPTION_TAG_REV_END;
pub const MESSAGE_MIN_LEN_WITH_SIGN: usize = RESUMPTION_TOKEN_END + PAYLOAD_REV_START;

pub const MESSAGE_MIN_LEN: usize = MESSAGE_LEN_WITHOUT_SIGN;
pub const MESSAGE_MAX_LEN: usize = 2 * MESSAGE_MIN_LEN_WITH_SIGN.next_power_of_two();

#[allow(unused)]
pub const MESSAGE_GCM_TOTAL: u32 = 2;
