use std::ops::Range;

use crate::crypto::*;

/* MESSAGE DEFINITION */

pub const HANDSHAKE_FLAGS_START: usize = 0;
pub const HANDSHAKE_FLAGS_LEN: usize = 1;
pub const HANDSHAKE_FLAGS_END: usize = HANDSHAKE_FLAGS_IDX + HANDSHAKE_FLAGS_LEN;
pub const HANDSHAKE_FLAGS_IDX: usize = HANDSHAKE_FLAGS_START;

pub const EPHEMERAL_ENC_KEY_START: usize = HANDSHAKE_FLAGS_END;
pub const EPHEMERAL_ENC_KEY_LEN: usize = mlkem1024::ENCAPSULATION_KEY_LEN;
pub const EPHEMERAL_ENC_KEY_END: usize = EPHEMERAL_ENC_KEY_START + EPHEMERAL_ENC_KEY_LEN;
pub const EPHEMERAL_ENC_KEY_RANGE: Range<usize> = EPHEMERAL_ENC_KEY_START..EPHEMERAL_ENC_KEY_END;

pub const RESUMPTION_TOKEN_START: usize = EPHEMERAL_ENC_KEY_END;
pub const RESUMPTION_TOKEN_LEN: usize = 32;
pub const RESUMPTION_TOKEN_END: usize = RESUMPTION_TOKEN_START + RESUMPTION_TOKEN_LEN;
pub const RESUMPTION_TOKEN_RANGE: Range<usize> = RESUMPTION_TOKEN_START..RESUMPTION_TOKEN_END;

pub const FULL_HANDSHAKE_RESUMPTION_TAG_START: usize = RESUMPTION_TOKEN_END;
pub const FULL_HANDSHAKE_RESUMPTION_TAG_LEN: usize = 16;
pub const FULL_HANDSHAKE_RESUMPTION_TAG_END: usize =
    FULL_HANDSHAKE_RESUMPTION_TAG_START + FULL_HANDSHAKE_RESUMPTION_TAG_LEN;
pub const FULL_HANDSHAKE_RESUMPTION_TAG_RANGE: Range<usize> =
    FULL_HANDSHAKE_RESUMPTION_TAG_START..FULL_HANDSHAKE_RESUMPTION_TAG_END;

pub const KEY_BUNDLE_CHECKSUM_START: usize = RESUMPTION_TOKEN_END;
pub const KEY_BUNDLE_CHECKSUM_LEN: usize = 16;
pub const KEY_BUNDLE_CHECKSUM_END: usize = KEY_BUNDLE_CHECKSUM_START + KEY_BUNDLE_CHECKSUM_LEN;
pub const KEY_BUNDLE_CHECKSUM_RANGE: Range<usize> = KEY_BUNDLE_CHECKSUM_START..KEY_BUNDLE_CHECKSUM_END;

pub const PAYLOAD_LEN_START: usize = KEY_BUNDLE_CHECKSUM_END;
pub const PAYLOAD_LEN_LEN: usize = 2;
pub const PAYLOAD_LEN_END: usize = PAYLOAD_LEN_START + PAYLOAD_LEN_LEN;
pub const PAYLOAD_LEN_RANGE: Range<usize> = PAYLOAD_LEN_START..PAYLOAD_LEN_END;

pub const PAYLOAD_START: usize = PAYLOAD_LEN_END;

/* MESSAGE TAIL DEFINITION */

pub const PAYLOAD_REV_START: usize = PAYLOAD_TAG_REV_END;

pub const PAYLOAD_TAG_REV_END: usize = PAYLOAD_TAG_REV_START + PAYLOAD_TAG_LEN;
pub const PAYLOAD_TAG_LEN: usize = aes256::TAG_LEN;
pub const PAYLOAD_TAG_REV_START: usize = ONLINE_SIGN_REV_END;

pub const ONLINE_SIGN_REV_END: usize = ONLINE_SIGN_REV_START + ONLINE_SIGN_LEN;
pub const ONLINE_SIGN_LEN: usize = mldsa87::SIGN_LEN;
pub const ONLINE_SIGN_REV_START: usize = ONLINE_SIGN_TAG_REV_END;

pub const ONLINE_SIGN_TAG_REV_END: usize = ONLINE_SIGN_TAG_REV_START + ONLINE_SIGN_TAG_LEN;
pub const ONLINE_SIGN_TAG_LEN: usize = aes256::TAG_LEN;
pub const ONLINE_SIGN_TAG_REV_START: usize = 0;

/* MISC CONSTANTS */

pub const PREMESSAGE_FULL_HANDSHAKE_RANGE: Range<usize> = 0..EPHEMERAL_ENC_KEY_END;

pub const PREMESSAGE_RESUMPTION_END: usize = RESUMPTION_TOKEN_END;
pub const PREMESSAGE_RESUMPTION_RANGE: Range<usize> = 0..PREMESSAGE_RESUMPTION_END;

pub const NULL_KEY_ID: u32 = 0;

pub const RESUMPTION_KEY_LEN: usize = 64;

pub const FULL_HANSHAKE_LEN: usize = EPHEMERAL_ENC_KEY_END;
pub const FULL_HANSHAKE_RESUMPTION_LEN: usize = FULL_HANDSHAKE_RESUMPTION_TAG_END;
pub const RESUMTION_LEN_MIN: usize = PAYLOAD_START + PAYLOAD_REV_START;

#[allow(unused)]
pub const MESSAGE_GCM_TOTAL: u32 = 2;
