use std::ops::Range;

use crate::crypto::mldsa87::*;

/* START OF KEY BUNDLE DEFINITION */

pub const OFFLINE_PUBLIC_KEY_START: usize = 0;
pub const OFFLINE_PUBLIC_KEY_LEN: usize = PUBLIC_KEY_LEN;
pub const OFFLINE_PUBLIC_KEY_END: usize = OFFLINE_PUBLIC_KEY_START + OFFLINE_PUBLIC_KEY_LEN;
pub const OFFLINE_PUBLIC_KEY_RANGE: Range<usize> = OFFLINE_PUBLIC_KEY_START..OFFLINE_PUBLIC_KEY_END;

pub const ONLINE_PUBLIC_KEY_START: usize = OFFLINE_PUBLIC_KEY_END;
pub const ONLINE_PUBLIC_KEY_LEN: usize = PUBLIC_KEY_LEN;
pub const ONLINE_PUBLIC_KEY_END: usize = ONLINE_PUBLIC_KEY_START + ONLINE_PUBLIC_KEY_LEN;
pub const ONLINE_PUBLIC_KEY_RANGE: Range<usize> = ONLINE_PUBLIC_KEY_START..ONLINE_PUBLIC_KEY_END;

pub const UID_START: usize = ONLINE_PUBLIC_KEY_END;
pub const UID_LEN: usize = 16;
pub const UID_END: usize = UID_START + UID_LEN;
pub const UID_RANGE: Range<usize> = UID_START..UID_END;

pub const NOT_BEFORE_SECS_START: usize = UID_END;
pub const NOT_BEFORE_SECS_LEN: usize = 8;
pub const NOT_BEFORE_SECS_END: usize = NOT_BEFORE_SECS_START + NOT_BEFORE_SECS_LEN;
pub const NOT_BEFORE_SECS_RANGE: Range<usize> = NOT_BEFORE_SECS_START..NOT_BEFORE_SECS_END;

pub const NOT_AFTER_SECS_START: usize = NOT_BEFORE_SECS_END;
pub const NOT_AFTER_SECS_LEN: usize = 8;
pub const NOT_AFTER_SECS_END: usize = NOT_AFTER_SECS_START + NOT_AFTER_SECS_LEN;
pub const NOT_AFTER_SECS_RANGE: Range<usize> = NOT_AFTER_SECS_START..NOT_AFTER_SECS_END;

pub const HANDSHAKE_VARIANT_START: usize = NOT_AFTER_SECS_END;
pub const HANDSHAKE_VARIANT_LEN: usize = 1;
pub const HANDSHAKE_VARIANT_END: usize = HANDSHAKE_VARIANT_START + HANDSHAKE_VARIANT_LEN;
pub const HANDSHAKE_VARIANT_IDX: usize = HANDSHAKE_VARIANT_START;

pub const RESERVED_START: usize = HANDSHAKE_VARIANT_END;
pub const RESERVED_LEN: usize = 4;
pub const RESERVED_END: usize = RESERVED_START + RESERVED_LEN;

/* START OF KEY BUNDLE TAIL DEFINITION */

pub const OFFLINE_SIGN_START: usize = RESERVED_END;
pub const OFFLINE_SIGN_LEN: usize = SIGNATURE_LEN;
pub const OFFLINE_SIGN_END: usize = OFFLINE_SIGN_START + OFFLINE_SIGN_LEN;
pub const OFFLINE_SIGNATURE_RANGE: Range<usize> = OFFLINE_SIGN_START..OFFLINE_SIGN_END;

/* START OF GENERAL CONSTANTS */

pub const KEY_BUNDLE_LEN: usize = OFFLINE_SIGN_END;

pub const SIGNED_DATA_RANGE: Range<usize> = ONLINE_PUBLIC_KEY_START..OFFLINE_SIGN_START;
