use std::ops::Range;

use crate::crypto::*;

/* START OF MESSAGE DEFINITION */

pub const HANDSHAKE_FLAGS_START: usize = 0;
pub const HANDSHAKE_FLAGS_LEN: usize = 1;
pub const HANDSHAKE_FLAGS_END: usize = HANDSHAKE_FLAGS_IDX + HANDSHAKE_FLAGS_LEN;
pub const HANDSHAKE_FLAGS_IDX: usize = HANDSHAKE_FLAGS_START;

pub const EPHEMERAL_CIPHERTEXT_START: usize = HANDSHAKE_FLAGS_END;
pub const EPHEMERAL_CIPHERTEXT_LEN: usize = mlkem1024::CIPHERTEXT_LEN;
pub const EPHEMERAL_CIPHERTEXT_END: usize = EPHEMERAL_CIPHERTEXT_START + EPHEMERAL_CIPHERTEXT_LEN;
pub const EPHEMERAL_CIPHERTEXT_RANGE: Range<usize> = EPHEMERAL_CIPHERTEXT_START..EPHEMERAL_CIPHERTEXT_END;

pub const PAYLOAD_LEN_START: usize = HANDSHAKE_FLAGS_END;
pub const PAYLOAD_LEN_LEN: usize = 2;
pub const PAYLOAD_LEN_END: usize = PAYLOAD_LEN_START + PAYLOAD_LEN_LEN;
pub const PAYLOAD_LEN_RANGE: Range<usize> = PAYLOAD_LEN_START..PAYLOAD_LEN_END;

pub const PAYLOAD_START: usize = PAYLOAD_LEN_END;

pub const PREMESSAGE_RANGE: Range<usize> = 0..EPHEMERAL_CIPHERTEXT_END;

/* START OF MESSAGE TAIL DEFINITION */

pub const KEY_BUNDLE_REV_START: usize = PAYLOAD_TAG_REV_END;

pub const PAYLOAD_TAG_REV_END: usize = PAYLOAD_TAG_REV_START + PAYLOAD_TAG_LEN;
pub const PAYLOAD_TAG_LEN: usize = aes256::TAG_LEN;
pub const PAYLOAD_TAG_REV_START: usize = ONLINE_SIGNATURE_REV_END;

pub const ONLINE_SIGNATURE_REV_END: usize = ONLINE_SIGNATURE_REV_START + ONLINE_SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_LEN: usize = mldsa87::SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_REV_START: usize = ONLINE_SIGNATURE_TAG_REV_END;

pub const ONLINE_SIGNATURE_TAG_REV_END: usize = ONLINE_SIGNATURE_TAG_REV_START + ONLINE_SIGNATURE_TAG_LEN;
pub const ONLINE_SIGNATURE_TAG_LEN: usize = aes256::TAG_LEN;
pub const ONLINE_SIGNATURE_TAG_REV_START: usize = 0;

/* START OF LENGTH CONSTANTS */

pub const HEADER_LEN: usize = super::shared::SEGMENT_HEADER_END;

pub const MESSAGE_GCM_TOTAL: u32 = 3;
