use std::ops::Range;

use crate::{crypto::*, key_bundle::KEY_BUNDLE_MIN_LEN};

/* START OF MESSAGE DEFINITION */

pub const HANDSHAKE_VERSION_START: usize = super::shared::SEGMENT_HEADER_END;
pub const HANDSHAKE_VERSION_LEN: usize = 1;
pub const HANDSHAKE_VERSION_END: usize = HANDSHAKE_VERSION_IDX + HANDSHAKE_VERSION_LEN;
pub const HANDSHAKE_VERSION_IDX: usize = HANDSHAKE_VERSION_START;
pub const HANDSHAKE_VERSION_VALUE: u8 = 0;

pub const HANDSHAKE_FLAGS_START: usize = HANDSHAKE_VERSION_END;
pub const HANDSHAKE_FLAGS_LEN: usize = 1;
pub const HANDSHAKE_FLAGS_END: usize = HANDSHAKE_FLAGS_IDX + HANDSHAKE_FLAGS_LEN;
pub const HANDSHAKE_FLAGS_IDX: usize = HANDSHAKE_FLAGS_START;

pub const EPHEMERAL_CIPHERTEXT_START: usize = HANDSHAKE_FLAGS_END;
pub const EPHEMERAL_CIPHERTEXT_LEN: usize = mlkem1024::CIPHERTEXT_LEN;
pub const EPHEMERAL_CIPHERTEXT_END: usize = EPHEMERAL_CIPHERTEXT_START + EPHEMERAL_CIPHERTEXT_LEN;
pub const EPHEMERAL_CIPHERTEXT_RANGE: Range<usize> = EPHEMERAL_CIPHERTEXT_START..EPHEMERAL_CIPHERTEXT_END;

pub const PREMESSAGE_RANGE: Range<usize> = 0..EPHEMERAL_CIPHERTEXT_END;

pub const PAYLOAD_ENCRYPTION_START: usize = EPHEMERAL_CIPHERTEXT_END;

pub const NEW_SOCKET_ID_START: usize = EPHEMERAL_CIPHERTEXT_END;
pub const NEW_SOCKET_ID_LEN: usize = 4;
pub const NEW_SOCKET_ID_END: usize = NEW_SOCKET_ID_START + NEW_SOCKET_ID_LEN;
pub const NEW_SOCKET_ID_RANGE: Range<usize> = NEW_SOCKET_ID_START..NEW_SOCKET_ID_END;

pub const KEY_BUNDLE_START: usize = NEW_SOCKET_ID_END;

/* START OF MESSAGE TAIL DEFINITION */

pub const PAYLOAD_REV_START: usize = PAYLOAD_TAG_REV_END;

pub const PAYLOAD_TAG_REV_END: usize = PAYLOAD_TAG_REV_START + PAYLOAD_TAG_LEN;
pub const PAYLOAD_TAG_LEN: usize = aes256::TAG_LEN;
pub const PAYLOAD_TAG_REV_START: usize = ONLINE_SIGNATURE_REV_END;

pub const ONLINE_SIGNATURE_REV_END: usize = ONLINE_SIGNATURE_REV_START + ONLINE_SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_LEN: usize = mldsa87::SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_REV_START: usize = ONLINE_SIGNATURE_TAG_REV_END;

pub const ONLINE_SIGNATURE_TAG_REV_END: usize = ONLINE_SIGNATURE_TAG_REV_START + ONLINE_SIGNATURE_TAG_LEN;
pub const ONLINE_SIGNATURE_TAG_LEN: usize = aes256::TAG_LEN;
pub const ONLINE_SIGNATURE_TAG_REV_START: usize = 0;

/* START OF LENGTH CONSTANTS */

pub const HEADER_LEN: usize = super::shared::SEGMENT_HEADER_END;

pub const MESSAGE_MIN_LEN_WITHOUT_BUNDLE: usize = KEY_BUNDLE_START + PAYLOAD_REV_START;

pub const MESSAGE_MIN_LEN: usize = MESSAGE_MIN_LEN_WITHOUT_BUNDLE + KEY_BUNDLE_MIN_LEN;
pub const MESSAGE_MAX_LEN: usize = 2 * MESSAGE_MIN_LEN.next_power_of_two();

pub const MESSAGE_GCM_TOTAL: u32 = 3;
