use std::ops::Range;

use super::*;
use crate::crypto::*;

/* START OF MESSAGE DEFINITION */

pub const HANDSHAKE_VERSION_START: usize = reply::HANDSHAKE_VERSION_START;
pub const HANDSHAKE_VERSION_LEN: usize = reply::HANDSHAKE_VERSION_LEN;
pub const HANDSHAKE_VERSION_END: usize = reply::HANDSHAKE_VERSION_END;
pub const HANDSHAKE_VERSION_IDX: usize = reply::HANDSHAKE_VERSION_IDX;
pub const HANDSHAKE_VERSION_VALUE: u8 = reply::HANDSHAKE_VERSION_VALUE;

pub const HANDSHAKE_FLAGS_START: usize = reply::HANDSHAKE_FLAGS_START;
pub const HANDSHAKE_FLAGS_LEN: usize = reply::HANDSHAKE_FLAGS_LEN;
pub const HANDSHAKE_FLAGS_END: usize = reply::HANDSHAKE_FLAGS_END;
pub const HANDSHAKE_FLAGS_IDX: usize = reply::HANDSHAKE_FLAGS_IDX;

pub const EPHEMERAL_CIPHERTEXT_START: usize = reply::EPHEMERAL_CIPHERTEXT_START;
pub const EPHEMERAL_CIPHERTEXT_LEN: usize = reply::EPHEMERAL_CIPHERTEXT_LEN;
pub const EPHEMERAL_CIPHERTEXT_END: usize = reply::EPHEMERAL_CIPHERTEXT_END;
pub const EPHEMERAL_CIPHERTEXT_RANGE: Range<usize> = reply::EPHEMERAL_CIPHERTEXT_RANGE;

pub const PAYLOAD_ENCRYPTION_START: usize = reply::PAYLOAD_ENCRYPTION_START;

pub const NEW_SOCKET_ID_START: usize = reply::NEW_SOCKET_ID_START;
pub const NEW_SOCKET_ID_LEN: usize = reply::NEW_SOCKET_ID_LEN;
pub const NEW_SOCKET_ID_END: usize = reply::NEW_SOCKET_ID_END;
pub const NEW_SOCKET_ID_RANGE: Range<usize> = reply::NEW_SOCKET_ID_RANGE;

pub const PAYLOAD_START: usize = NEW_SOCKET_ID_END;

/* START OF MESSAGE TAIL DEFINITION */

pub const PAYLOAD_REV_START: usize = PAYLOAD_TAG_REV_END;

pub const PAYLOAD_TAG_REV_END: usize = PAYLOAD_TAG_REV_START + PAYLOAD_TAG_LEN;
pub const PAYLOAD_TAG_LEN: usize = aes256::TAG_LEN;
pub const PAYLOAD_TAG_REV_START: usize = ONLINE_SIGNATURE_REV_END;

pub const ONLINE_SIGNATURE_REV_END: usize = ONLINE_SIGNATURE_REV_START + ONLINE_SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_LEN: usize = mldsa87::SIGNATURE_LEN;
pub const ONLINE_SIGNATURE_REV_START: usize = ONLINE_SIGNATURE_TAG_REV_END;

pub const ONLINE_SIGNATURE_TAG_REV_END: usize = ONLINE_SIGNATURE_TAG_REV_START + ONLINE_SIGNATURE_TAG_LEN;
pub const ONLINE_SIGNATURE_TAG_LEN: usize = aes256::TAG_LEN;
pub const ONLINE_SIGNATURE_TAG_REV_START: usize = 0;

/* START OF GENERAL CONSTANTS */

#[allow(unused)]
pub const HEADER_LEN: usize = shared::SEGMENT_HEADER_END;

pub const MESSAGE_MIN_LEN: usize = PAYLOAD_START + PAYLOAD_REV_START;
pub const MESSAGE_MAX_LEN: usize = 2 * MESSAGE_MIN_LEN.next_power_of_two();

pub const MESSAGE_GCM_TOTAL: u32 = 2;
pub const COUNTER_SKIP: u32 = reply::MESSAGE_GCM_TOTAL + confirm::MESSAGE_GCM_TOTAL;
