use std::ops::Range;

use super::*;
use crate::crypto::*;

/* START OF MESSAGE DEFINITION */

pub const EPHEMERAL_CIPHERTEXT_START: usize = reply::EPHEMERAL_CIPHERTEXT_START;
pub const EPHEMERAL_CIPHERTEXT_LEN: usize = reply::EPHEMERAL_CIPHERTEXT_LEN;
pub const EPHEMERAL_CIPHERTEXT_END: usize = reply::EPHEMERAL_CIPHERTEXT_END;
pub const EPHEMERAL_CIPHERTEXT_RANGE: Range<usize> = reply::EPHEMERAL_CIPHERTEXT_RANGE;

pub const HANDSHAKE_VARIANT_START: usize = reply::HANDSHAKE_VARIANT_START;
pub const HANDSHAKE_VARIANT_LEN: usize = reply::HANDSHAKE_VARIANT_LEN;
pub const HANDSHAKE_VARIANT_END: usize = reply::HANDSHAKE_VARIANT_END;
pub const HANDSHAKE_VARIANT_IDX: usize = reply::HANDSHAKE_VARIANT_IDX;

pub const NEW_SOCKET_ID_START: usize = reply::NEW_SOCKET_ID_START;
pub const NEW_SOCKET_ID_LEN: usize = reply::NEW_SOCKET_ID_LEN;
pub const NEW_SOCKET_ID_END: usize = reply::NEW_SOCKET_ID_END;
pub const NEW_SOCKET_ID_RANGE: Range<usize> = reply::NEW_SOCKET_ID_RANGE;

/* START OF MESSAGE TAIL DEFINITION */

pub const PAYLOAD_TAG_REV_END: usize = PAYLOAD_TAG_REV_START + PAYLOAD_TAG_LEN;
pub const PAYLOAD_TAG_LEN: usize = aes256::TAG_LEN;
pub const PAYLOAD_TAG_REV_START: usize = STATIC_ONLINE_SIGN_REV_END;

pub const STATIC_ONLINE_SIGN_REV_END: usize = STATIC_ONLINE_SIGN_REV_START + STATIC_ONLINE_SIGN_LEN;
pub const STATIC_ONLINE_SIGN_LEN: usize = mldsa87::SIGNATURE_LEN;
pub const STATIC_ONLINE_SIGN_REV_START: usize = STATIC_ONLINE_SIGN_TAG_REV_END;

pub const STATIC_ONLINE_SIGN_TAG_REV_END: usize = STATIC_ONLINE_SIGN_TAG_REV_START + STATIC_ONLINE_SIGN_TAG_LEN;
pub const STATIC_ONLINE_SIGN_TAG_LEN: usize = aes256::TAG_LEN;
pub const STATIC_ONLINE_SIGN_TAG_REV_START: usize = 0;

/* START OF GENERAL CONSTANTS */

#[allow(unused)]
pub const HEADER_LEN: usize = shared::SEGMENT_HEADER_END;
pub const MESSAGE_LEN: usize = NEW_SOCKET_ID_END + PAYLOAD_TAG_REV_END;

pub const MESSAGE_MIN_LEN: usize = MESSAGE_LEN;
pub const MESSAGE_MAX_LEN: usize = 2 * MESSAGE_LEN.next_power_of_two();

pub const MESSAGE_GCM_TOTAL: u32 = 2;
pub const COUNTER_SKIP: u32 = reply::MESSAGE_GCM_TOTAL + confirm::MESSAGE_GCM_TOTAL;
