use std::ops::Range;

use crate::crypto::*;

/* START OF SEGMENTATION HEADER DEFINITION */

pub const SOCKET_ID_START: usize = 0;
pub const SOCKET_ID_LEN: usize = 4;
pub const SOCKET_ID_END: usize = SOCKET_ID_START + SOCKET_ID_LEN;
pub const SOCKET_ID_RANGE: Range<usize> = SOCKET_ID_START..SOCKET_ID_END;

pub const SEGMENT_NO_IDX: usize = 4;
pub const SEGMENT_REMAINDER_IDX: usize = 5;
pub const SEGMENT_TOTAL_IDX: usize = 6;
pub const SEGMENT_HEADER_END: usize = 8;

/* START OF SHAKE256 OUTPUT DEFINITION */

pub const CHAINING_KEY_START: usize = 0;
pub const CHAINING_KEY_LEN: usize = 64;
pub const CHAINING_KEY_END: usize = CHAINING_KEY_START + CHAINING_KEY_LEN;
pub const CHAINING_KEY_RANGE: Range<usize> = CHAINING_KEY_START..CHAINING_KEY_END;

pub const AES_KEY_START: usize = CHAINING_KEY_END;
pub const AES_KEY_LEN: usize = aes256::KEY_LEN;
pub const AES_KEY_END: usize = AES_KEY_START + AES_KEY_LEN;
pub const AES_KEY_RANGE: Range<usize> = AES_KEY_START..AES_KEY_END;

pub const CHANNEL_BINDING_START: usize = AES_KEY_END;
pub const CHANNEL_BINDING_LEN: usize = 32;
pub const CHANNEL_BINDING_END: usize = CHANNEL_BINDING_START + CHANNEL_BINDING_LEN;
pub const CHANNEL_BINDING_RANGE: Range<usize> = CHANNEL_BINDING_START..CHANNEL_BINDING_END;

/* START OF SHAKE256 SPLIT OUTPUT DEFINITION */

pub const NEW_RESUMPTION_KEY_START: usize = 0;
pub const NEW_RESUMPTION_KEY_LEN: usize = 64;
pub const NEW_RESUMPTION_KEY_END: usize = NEW_RESUMPTION_KEY_START + NEW_RESUMPTION_KEY_LEN;
pub const NEW_RESUMPTION_KEY_RANGE: Range<usize> = NEW_RESUMPTION_KEY_START..NEW_RESUMPTION_KEY_END;

pub const NEW_RESUMPTION_TOKEN_START: usize = NEW_RESUMPTION_KEY_END;
pub const NEW_RESUMPTION_TOKEN_LEN: usize = 32;
pub const NEW_RESUMPTION_TOKEN_END: usize = NEW_RESUMPTION_TOKEN_START + NEW_RESUMPTION_TOKEN_LEN;
pub const NEW_RESUMPTION_TOKEN_RANGE: Range<usize> = NEW_RESUMPTION_TOKEN_START..NEW_RESUMPTION_TOKEN_END;

pub const RECV_KEY_START: usize = NEW_RESUMPTION_TOKEN_END;
pub const RECV_KEY_LEN: usize = aes256::KEY_LEN;
pub const RECV_KEY_END: usize = RECV_KEY_START + RECV_KEY_LEN;
pub const RECV_KEY_RANGE: Range<usize> = RECV_KEY_START..RECV_KEY_END;

pub const SEND_KEY_START: usize = RECV_KEY_END;
pub const SEND_KEY_LEN: usize = aes256::KEY_LEN;
pub const SEND_KEY_END: usize = SEND_KEY_START + SEND_KEY_LEN;
pub const SEND_KEY_RANGE: Range<usize> = SEND_KEY_START..SEND_KEY_END;

/* START OF GENERAL CONSTANTS */

pub const SHAKE256_MAX_OUTPUT_LEN: usize = SEND_KEY_END;

pub const AES_GCM_INIT_COUNTER: u32 = 1;

pub const HANDSHAKE_VARIANT_FULL_EXCHANGE_FLAG: u8 = 0b1;
pub const HANDSHAKE_VARIANT_RESUME_FLAG: u8 = 0b10;
pub const HANDSHAKE_VARIANT_DENY_FALLBACK_FLAG: u8 = 0b100;
