use std::ops::Range;

use crate::{
    crypto::aes256,
};

/* SHAKE256 OUTPUT DEFINITION */

pub const CHAINING_KEY_START: usize = 0;
pub const CHAINING_KEY_LEN: usize = 64;
pub const CHAINING_KEY_END: usize = CHAINING_KEY_START + CHAINING_KEY_LEN;
pub const CHAINING_KEY_RANGE: Range<usize> = CHAINING_KEY_START..CHAINING_KEY_END;

pub const AES_KEY_START: usize = CHAINING_KEY_END;
pub const AES_KEY_LEN: usize = aes256::KEY_LEN;
pub const AES_KEY_END: usize = AES_KEY_START + AES_KEY_LEN;
pub const AES_KEY_RANGE: Range<usize> = AES_KEY_START..AES_KEY_END;

pub const CHANNEL_BINDING_START: usize = AES_KEY_END;
pub const CHANNEL_BINDING_LEN: usize = 48;
pub const CHANNEL_BINDING_END: usize = CHANNEL_BINDING_START + CHANNEL_BINDING_LEN;
pub const CHANNEL_BINDING_RANGE: Range<usize> = CHANNEL_BINDING_START..CHANNEL_BINDING_END;

/* SHAKE256 SPLIT OUTPUT DEFINITION */

pub const RESUMPTION_KEY_START: usize = 0;
pub const RESUMPTION_KEY_LEN: usize = 64;
pub const RESUMPTION_KEY_END: usize = RESUMPTION_KEY_START + RESUMPTION_KEY_LEN;
pub const RESUMPTION_KEY_RANGE: Range<usize> = RESUMPTION_KEY_START..RESUMPTION_KEY_END;

pub const INITIATOR_RESUMPTION_TOKEN_START: usize = RESUMPTION_KEY_END;
pub const INITIATOR_RESUMPTION_TOKEN_LEN: usize = 32;
pub const INITIATOR_RESUMPTION_TOKEN_END: usize = INITIATOR_RESUMPTION_TOKEN_START + INITIATOR_RESUMPTION_TOKEN_LEN;
pub const INITIATOR_RESUMPTION_TOKEN_RANGE: Range<usize> =
    INITIATOR_RESUMPTION_TOKEN_START..INITIATOR_RESUMPTION_TOKEN_END;

pub const RESPONDER_RESUMPTION_TOKEN_START: usize = INITIATOR_RESUMPTION_TOKEN_END;
pub const RESPONDER_RESUMPTION_TOKEN_LEN: usize = 32;
pub const RESPONDER_RESUMPTION_TOKEN_END: usize = RESPONDER_RESUMPTION_TOKEN_START + RESPONDER_RESUMPTION_TOKEN_LEN;
pub const RESPONDER_RESUMPTION_TOKEN_RANGE: Range<usize> =
    RESPONDER_RESUMPTION_TOKEN_START..RESPONDER_RESUMPTION_TOKEN_END;

pub const INITIATOR_KEY_START: usize = RESPONDER_RESUMPTION_TOKEN_END;
pub const INITIATOR_KEY_LEN: usize = aes256::KEY_LEN;
pub const INITIATOR_KEY_END: usize = INITIATOR_KEY_START + INITIATOR_KEY_LEN;
pub const INITIATOR_KEY_RANGE: Range<usize> = INITIATOR_KEY_START..INITIATOR_KEY_END;

pub const RESPONDER_KEY_START: usize = INITIATOR_KEY_END;
pub const RESPONDER_KEY_LEN: usize = aes256::KEY_LEN;
pub const RESPONDER_KEY_END: usize = RESPONDER_KEY_START + RESPONDER_KEY_LEN;
pub const RESPONDER_KEY_RANGE: Range<usize> = RESPONDER_KEY_START..RESPONDER_KEY_END;

/* MISC CONSTANTS */

pub const SHAKE256_HANDSHAKE_OUTPUT_LEN: usize = CHANNEL_BINDING_END;
pub const SHAKE256_SPLIT_OUTPUT_LEN: usize = RESPONDER_KEY_END;
